model:
  act: tanh # None, tanh, relu or sigmoid
  hidden_layer: True
  dino_embed_dim: 768

train:
  lr: 0.0001
  ltype: 'infonce'
  num_epochs: 30
  batch_size: 128
  save_best_model: False

  lambda_obj: 300
  lambda_inst: 1.0
  lambda_overlap: 0.01
  lambda_spear: 0.01
  patch_temperature: 0.07
  em_iters: 1
  
dataset:
  min_obj_area_ratio: 0.0