model:
  act: null # None, tanh, relu or sigmoid
  hidden_layer: False
  dino_embed_dim: 768

train:
  lr: 0.0001
  ltype: 'infonce'
  num_epochs: 30
  batch_size: 128
  save_best_model: False

  lambda_obj: 240
  lambda_inst: 1.0
  lambda_overlap: 20.0
  lambda_spear: 40.0
  
dataset:
  min_obj_area_ratio: 0.0